### ISSUE TITLE
Case mismatch KeyboardViewPort.h

### ISSUE THREAD

**Issue by KottV** [vsicurella/SuperVirtualKeyboard#10]
Hi!

Compiling in Linux fails due couple of mismatch in filename:
**KeyboardViewport.h** instead of **KeyboardViewPort.h**
in
**SuperVirtualKeyboard.jucer PluginControlComponent.h KeyboardComponent.h KeyboardViewPort.cpp**

**Comment by vsicurella** [comment]
Ah a refactor gone wrong! Sorry for the issues, thanks for reporting this, I'm just getting around to polishing it up for Mac and Linux so it should be resolved soon.

**Comment by KottV** [comment]
I see, thanks!

**Comment by vsicurella** [comment]
Hey, so I tried building it on Mac after a fresh clone and didn't have any issues. I tried building on Linux and ran out of time before I could fix a JUCE/VST 2 issue, but I checked the build script and the filename looked correct.

Did you try to build it from a fresh clone or did you pull the update? If you pulled it, would you mind trying to build it from a fresh clone?

I'm going spend more time on the Linux build myself tomorrow!

**Comment by vsicurella** [comment]
Scratch that, fixing this at the moment!

**Comment by vsicurella** [comment]
You should be able to build it now! :)

Still need to do more thorough testing on Mac and Linux though.

**Comment by KottV** [comment]
Yep, that fixed.
