### ISSUE TITLE
License missing.

### ISSUE THREAD

**Issue by KottV** [vsicurella/SuperVirtualKeyboard#12]
Hi,

It would be great to include SuperVirtualKeyboard builds in Linux repositories, but such thing requires a license (GPL, MIT or whatever).

Thank you for your great tool!

**Comment by vsicurella** [comment]
Thanks for the reminder :) I had meant to do some more research on this a while back. I'd like it to be completely free software with no restrictions.

I would probably be fine with MIT or BSD, but I'd favor the Unlicense if it's okay for the Linux repos: https://unlicense.org/
Or even this one, although this is not approved by the OSI: http://www.wtfpl.net/about/

Do you have any thoughts or concerns about the Unlicense?

**Comment by KottV** [comment]
I think Unlicense is fine.
As far as I know -  SQLite uses this license and it shipped everywhere.

**Comment by vsicurella** [comment]
Thanks a lot for your input - added!
