### ISSUE TITLE
Backslash in Constants.h

### ISSUE THREAD

**Issue by KottV** [vsicurella/SuperVirtualKeyboard#13]
Just a little thing that works only in Windows and won't build in Mac/Linux:

https://github.com/vsicurella/SuperVirtualKeyboard/blob/master/Source/Constants.h#L13

#include "Structures\Mode.h"

**Comment by vsicurella** [comment]
Argh!! I hate that about Windows, and am usually on top of it. I'll fix this right away, sorry!
