### ISSUE TITLE
Backslash in AbletonMidiWriter.h

### ISSUE THREAD

**Issue by KottV** [vsicurella/SuperVirtualKeyboard#18]
Hi!

/Source/File IO/AbletonMidiWriter.h
```
#include "..\Structures\Mode.h"
```

won't work on non-windows sys :)

**Comment by vsicurella** [comment]
Argh!! Sorry...thank you.. lol 

Before COVID I was working on a Mac at work, and Windows at home, and now I'm using Windows for both, so my fingers keep forgetting 🤦

**Comment by vsicurella** [comment]
Also, I probably shouldn't be pushing to the Master branch without testing on other platforms...
